server {
    listen 80; # En la nube queremos entrar por el puerto estándar

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # Usamos 127.0.0.1 porque en la nube el backend está en modo --network host
        # IMPORTANTE: Sin la barra / al final
        proxy_pass http://127.0.0.1:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
