wol:
  host: "javipc-home.mooo.com"

quarkus:
  http:
    cors: true
  mailer:
    mock: false
    from: "viercadaver@gmail.com"
    host: "smtp.gmail.com"
    port: 587
    start-tls: "REQUIRED"
    username: "viercadaver@gmail.com"
    password: "hvrevarkasvnngkv"
